// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujQPZ6UndnJtEhkQ38pAom4Tl1t-U48U',
    appId: '1:804917451041:web:4472d09ae7f35a94ff0660',
    messagingSenderId: '804917451041',
    projectId: 'first-firebase-e436f',
    authDomain: 'first-firebase-e436f.firebaseapp.com',
    storageBucket: 'first-firebase-e436f.firebasestorage.app',
    measurementId: 'G-0YXEHRRMZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ16RpRtIJekCZO8aTcovQMz_gVv87YCs',
    appId: '1:804917451041:android:b6f2058fa2c99330ff0660',
    messagingSenderId: '804917451041',
    projectId: 'first-firebase-e436f',
    storageBucket: 'first-firebase-e436f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2nXbzuAu546guz74DoMR4jxOOMwCnis',
    appId: '1:804917451041:ios:5128e5b5082c7f7fff0660',
    messagingSenderId: '804917451041',
    projectId: 'first-firebase-e436f',
    storageBucket: 'first-firebase-e436f.firebasestorage.app',
    iosClientId: '804917451041-sbdvbouiq9vm1lkm04aa71po6c8ru5ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2nXbzuAu546guz74DoMR4jxOOMwCnis',
    appId: '1:804917451041:ios:5128e5b5082c7f7fff0660',
    messagingSenderId: '804917451041',
    projectId: 'first-firebase-e436f',
    storageBucket: 'first-firebase-e436f.firebasestorage.app',
    iosClientId: '804917451041-sbdvbouiq9vm1lkm04aa71po6c8ru5ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCujQPZ6UndnJtEhkQ38pAom4Tl1t-U48U',
    appId: '1:804917451041:web:a8fdacddd89b8725ff0660',
    messagingSenderId: '804917451041',
    projectId: 'first-firebase-e436f',
    authDomain: 'first-firebase-e436f.firebaseapp.com',
    storageBucket: 'first-firebase-e436f.firebasestorage.app',
    measurementId: 'G-KQQ6KK46CG',
  );
}
